In [ ]:
#Importando bibliotecas
import pandas as pd
import numpy as np

In [ ]:
#Leitura do arquivo CSV
df = pd.read_csv('../dados/base_varejo_limpa.csv', sep=';')

In [ ]:
#Analisando categorias vendidas por gênero 
agrupamento_genero = df.groupby(['PR_CAT', 'CL_GENERO']).agg(
    total_vendas=('CO_ID', 'count')
)

agrupamento_genero

                         total_vendas
PR_CAT        CL_GENERO
Acessorios    F                  6839
              M                  6032
Alimentos     F                200274
              M                183923
Bebidas       F                 19764
              M                 18500
Higiene       F                 71721
              M                 65981
Limpeza       F                 67328
              M                 61304
Pet           F                 14809
              M                 13744
Sem Categoria F                  1692
              M                  1536

In [ ]:
#Analisando produtos vendidos por gênero
produto_genero = (
    df.groupby(['PR_NOME', 'CL_GENERO'])
    .agg(vendas=('CO_ID', 'count'))
    .reset_index()
    .sort_values(by='vendas', ascending=False)
)

produto_genero.head(15)

                PR_NOME CL_GENERO  vendas
168     Presunto Cozido         F    6613
169     Presunto Cozido         M    6106
54              Chupeta         F    3485
214            Sardinha         F    3472
194           Removedor         F    3452
74           Detergente         F    3443
142           Modelador         F    3424
172     Queijo De Cabra         F    3417
70      Desengordurante         F    3415
82      Escova De Dente         F    3414
202                Rodo         F    3407
200              Ricota         F    3406
30                Balde         F    3405
46               Cebola         F    3405
126  Limpador Perfumado         F    3405

In [ ]:
#Estatísticas descritivas da coluna de número de filhos do cliente

estatisticas = pd.DataFrame({
    'Métrica': [
        'Média',
        'Mediana',
        'Desvio padrão',
        'Moda',
        'Mínimo',
        'Quartil 1 (25%)',
        'Quartil 2 (50%)',
        'Quartil 3 (75%)',
        'Máximo',
        'Contagem'
    ],
    'Valor': [
        df['CL_FHL'].mean(),
        df['CL_FHL'].median(),
        df['CL_FHL'].std(),
        df['CL_FHL'].mode().iloc[0],
        df['CL_FHL'].min(),
        df['CL_FHL'].quantile(0.25),
        df['CL_FHL'].quantile(0.50),
        df['CL_FHL'].quantile(0.75),
        df['CL_FHL'].max(),
        df['CL_FHL'].count()
    ]
})

estatisticas

           Métrica          Valor
0            Média       1.146049
1          Mediana       0.000000
2    Desvio padrão       1.416917
3             Moda       0.000000
4           Mínimo       0.000000
5  Quartil 1 (25%)       0.000000
6  Quartil 2 (50%)       0.000000
7  Quartil 3 (75%)       2.000000
8           Máximo       4.000000
9         Contagem  733447.000000